<?php /* @var $this Aoe_LayoutEditor_Block_Cms_Page_Edit_Tab_Layouteditor */ ?>

<?php echo $this->getChildHtml('blockpicker'); ?>

<script>
    // TODO: this shouldn't be hardcoded
    var PAGE_CONTAINERS = {
        empty: {},
        one_column: {
            content: { type: 'core/text_list' }
        },
        two_columns_left: {
            left: { type: 'core/text_list' },
            content: { type: 'core/text_list' }
        },
        two_columns_right: {
            content: { type: 'core/text_list' },
            right: { type: 'core/text_list' }
        },
        three_columns: {
            left: { type: 'core/text_list' },
            content: { type: 'core/text_list' },
            right: { type: 'core/text_list' }
        }
    };
</script>

<div id="root"></div>

<pre id="debug"></pre>