<?php /* @var $this Aoe_SnappyCms_Block_BlockPicker */?>
<div id="blockpicker">
    <ul class="tabs-horiz">
        <?php foreach($this->getCategories() as $category): ?>
        <li>
            <a class="tab-item-link" href="#tabs-<?php echo $category; ?>">
                <span><?php echo $this->__($category); ?></span>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>

    <?php foreach($this->getCategories() as $category): ?>
    <div id="tabs-<?php echo $category; ?>">
        <?php foreach($this->getElementsForCategory($category) as $type => $block): ?>
            <div class="block-blueprint" data-type="<?php echo $type; ?>">
                <div class="icon"><img src="<?php echo $block['icon'] ?>" alt=""/></div>
                <div class="label"><?php echo $block['label']; ?></div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php endforeach; ?>

</div>

<script>
    var AOE_SNAPPYCMS_BLOCKDEFINITION = <?php echo Zend_Json::encode($this->getAllBlocks()); ?>;
    var AOE_SNAPPYCMS_PAGEDEFINITION = <?php echo Zend_Json::encode($this->getAllPages()); ?>;
    jQuery(function() {
        jQuery('#blockpicker').tabs();
    })
</script>